# Generated by Django 4.0.4 on 2022-11-18 08:31

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_taggedwhatever_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
